### ISSUE TITLE
Question : What is the exact way to use maxDepth option and cache option at the same time?

### ISSUE THREAD

**Issue by qutie75** [yujiosaka/headless-chrome-crawler#212]
Thank you for your project!! 
I am trying to test in many ways. 

**What is the current behavior?**
I set there options on your redis-cache.js example. 
- maxDepth: 2
- persistCache: true

**What is the expected behavior?**
What I am expecting is cache is maintained whenever I run, and then I want to update if there is new link or something changed on that link. 

For example, 
I put 'url : A' with above options. 
- await crawler1.queue('url : A');

If this page have B and C links on it, A, B, C page is cached. 
And then I run again with same options. 
In this case, I expect to recheck all A, B, C links again. 
But I guess 'url : A' is checked first, and then no chance to check B, C links in A page. 

I hope to check this situation. 
Thank you for reading!

**Comment by yujiosaka** [comment]
@qutie75 

Thanks for a question, but I'm having a bit difficulty in understanding your point.
As far as I understand, your situation is exactly what `persistCache` is for.
If you want see if there are new links appeared on A page, you shouldn't enable `persistCache` from the first place.

A typical solution is to make a database for crawled pages.
You can crawled the urls stored in the database, so that you won't miss updated information on B, C page.

**Comment by yujiosaka** [comment]
Closing this issue in believe that my previous post already answered the question.
