### ISSUE TITLE
Trigger function on Page's requestfinished event

### ISSUE THREAD

**Issue by sebastienfi** [yujiosaka/headless-chrome-crawler#93]
Hi
First of all, thanks for relasing this, awesome work guys 👍 

I would like to access the Browser's Page's `requestfinished` event.
I believe that [event: 'requestfinished'](https://github.com/yujiosaka/headless-chrome-crawler#event-requestfinished) is the Crawler's `requestfinished` event.

My intention is to download the ressources of the page (images, fonts, ...).
I'm planning to do something like this :
```js
// On my previous setup, page originates from
// const browser = await puppeteer.launch()
// const page = await browser.newPage()
page.on('requestfinished', async request => { 
  // do something with request
  const url = request.url()
  const match = /.*\.(jpg|png|gif)$/.exec(url)
  if (match && match.length === 2) {
    const split = url.split('/')
    let filename = split[split.length - 1]
    const response = request.response()
    const buffer = await response.buffer()
    fs.writeFileSync(`${crawlPathImages}/${filename}`, buffer, 'base64')
  }
})
```
How can I do this using your crawler ?

**Comment by yujiosaka** [comment]
@sebastienfi 
Thanks for the comment! I'm flattered :)

Unfortunately, it does not provide APIs for your use case at this moment.

I made this crawler's `requestfinished` event different from puppeteer's `requestfinished`.
The crawler's `requestfinished' is emitted only when finished requesting documents like HTMLs.

However, I would like to make one since your request sounds very reasonable.

I'm thinking about exposing puppeteer's `page` instance so that you have more controls.
It should go like this:
```
const crawler = await HCCrawler.launch();
crawler.on('newpage', async page => {
  // this is puppeteer's page
  page.on('requestfinished', async request => {
    const url = request.url()
    ...
  });
});
crawler.queue('https://example.com/');
...
```

How does that sounds to you?

**Comment by sebastienfi** [comment]
That sounds great !
Do you need help to produce a PR ? I need that done quickly, if you point me out in the right direction, I can deliver ;)
